---
- name: WAZUH BACKEND | Find all ssl cert files
  ansible.builtin.find:
    paths: '{{ fabos_wazuh_default_config_dir }}/wazuh_indexer_ssl_certs'
    file_type: file
  register: wazuh_indexer_ssl_cert_files

- name: WAZUH BACKEND | Ensure read permissions for all ssl cert files
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: file
    mode: "0444"
  loop: '{{ wazuh_indexer_ssl_cert_files.files }}'
