---
- name: WAZUH BACKEND | Stat agent config file
  ansible.builtin.stat:
    path: "{{ fabos_wazuh_agent_config_file }}"
  register: stat_results

- name: "WAZUH BACKEND | Copy wazuh compose file and config"
  when: not stat_results.stat.exists
  ansible.builtin.copy:
    content: "{{ fabos_wazuh_agent_config | default('') }}"
    dest: "{{ fabos_wazuh_agent_config_file }}"
    owner: root
    group: root
    mode: "0644"
    remote_src: true

- name: WAZUH BACKEND | Add volume path for local rules file
  ansible.builtin.lineinfile:
    path: "{{ fabos_wazuh_default_docker_compose_dir }}/wazuh.yml"
    line: "{{ item.line }}"
    regexp: "{{ item.line }}"
    insertafter: "volumes:"
    firstmatch: true
  loop:
    - line: "      - {{ fabos_wazuh_agent_config_file }}:/var/ossec/etc/shared/default/agent.conf"
