---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: wazuh_backend
  gather_facts: false
  become: true
  vars:
    fabos_wazuh_service: backend
    fabos_wazuh_service_state: present
    fabos_wazuh_default_compose_ports:
      - container_port: 5601
        exposed_port: 5443
    fabos_wazuh_compose_project_name: eclipse-slm
  roles:
    - wazuh
