---
### Inputs:
- name: Assert Inputs
  ansible.builtin.assert:
    that:
      - (fabos_wazuh_manager_ip is defined) and (fabos_wazuh_manager_ip | length > 0)

### Optional Inputs:
# fabos_wazuh_manager_port: This must match the associated listening port configured on the Wazuh manager. (default: 1514)
# fabos_wazuh_agent_labels: # default: {}
#   label_key: label_value

- name: WAZUH AGENT | Install required packages for Wazuh repository
  ansible.builtin.apt:
    name:
      - gnupg
      - apt-transport-https
    state: present
    update_cache: true

- name: WAZUH AGENT | Add Wazuh APT repository and manage its key natively
  ansible.builtin.deb822_repository:
    name: wazuh
    types: [deb]
    uris: [https://packages.wazuh.com/4.x/apt/]
    suites: [stable]
    components: [main]
    signed_by: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: WAZUH AGENT | Install Wazuh agent
  ansible.builtin.apt:
    name: wazuh-agent
    state: present
    update_cache: true
  environment:
    WAZUH_MANAGER: "{{ fabos_wazuh_manager_ip }}"
    WAZUH_MANAGER_PORT: "{{ fabos_wazuh_manager_port | default(1514) }}"

- name: WAZUH AGENT | Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: WAZUH AGENT | Start Wazuh agent service
  ansible.builtin.systemd:
    name: wazuh-agent
    state: started
    enabled: true

- name: WAZUH AGENT | Configure agent labels
  when:
    - (fabos_wazuh_agent_labels is defined)
    - (fabos_wazuh_agent_labels | length > 0)
  ansible.builtin.blockinfile:
    path: "{{ fabos_wazuh_default_agent_config_dir }}/ossec.conf"
    block: "{{ lookup('template', 'agent_labels.j2') }}"
  notify: Restart Agent
