---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify - Backend is setup correctly
  ansible.builtin.import_playbook: ../install-wazuh-backend/verify.yml

- name: Verify - Agents are setup correctly
  ansible.builtin.import_playbook: ../install-wazuh-agent-ubuntu-24/verify.yml

- name: Verify - Backend/Agent connection is working
  ansible.builtin.import_playbook: ./verify-agents.yml

- name: Verify - Threat Detection is working
  ansible.builtin.import_playbook: ./verify-threat.yml

- name: Verify - Docker Volume Scanning is working
  ansible.builtin.import_playbook: ./verify-docker.yml
