---
# tasks file for installing wazuh backend on docker

### Optional Inputs:
# - fabos_wazuh_backend_monitord_keep_log_days: 30  # https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#monitord (default: 1)

- name: WAZUH BACKEND | Set vm.max_map_count sysctl parameter
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_file: /etc/sysctl.d/99-wazuh.conf
    state: present
    reload: true

- name: WAZUH BACKEND | Set final Wazuh version for compose URL
  ansible.builtin.set_fact:
    fabos_wazuh_final_version: "{{ fabos_wazuh_backend_version | default(fabos_wazuh_default_version) }}"

- name: WAZUH BACKEND | Clone Wazuh Docker repository
  ansible.builtin.git:
    repo: "{{ fabos_wazuh_default_wazuh_docker_git_url }}"
    dest: "{{ fabos_wazuh_default_wazuh_download_dir }}"
    version: "{{ fabos_wazuh_final_version }}"
  register: cloned_repo
  ignore_errors: true

- name: WAZUH BACKEND | Replace exposed ports in docker-compose file
  ansible.builtin.lineinfile:
    path: "{{ fabos_wazuh_default_single_node_compose_dir }}/docker-compose.yml"
    regexp: '(\s+-\s)"*.*:{{ item.container_port }}"*'
    line: '\g<1>{{ item.exposed_port }}:{{ item.container_port }}'
    backrefs: true
  loop: "{{ fabos_wazuh_default_compose_ports | default([]) }}"

- name: WAZUH BACKEND | Ensure docker-compose and config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ fabos_wazuh_default_config_dir }}"
    - "{{ fabos_wazuh_default_docker_compose_dir }}"

- name: WAZUH BACKEND | Stat config dir and docker-compose files
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - "{{ fabos_wazuh_default_config_dir }}/wazuh_dashboard"
    - "{{ fabos_wazuh_default_docker_compose_dir }}/{{ fabos_wazuh_default_compose_files[0] }}"
    - "{{ fabos_wazuh_default_docker_compose_dir }}/wazuh.yml"
  register: stat_results

# TODO: Check correct copy (files are converted to dicts ??)
- name: "WAZUH BACKEND | Copy wazuh compose file and config"
  when: not stat_results.results[i].stat.exists
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  loop_control:
    index_var: i
  loop:
    - src: "{{ fabos_wazuh_default_single_node_compose_dir }}/config/"
      dest: "{{ fabos_wazuh_default_config_dir }}"
    - src: "{{ fabos_wazuh_default_single_node_compose_dir }}/{{ fabos_wazuh_default_compose_files[0] }}"
      dest: "{{ fabos_wazuh_default_docker_compose_dir }}/{{ fabos_wazuh_default_compose_files[0] }}"
    - src: "{{ fabos_wazuh_default_single_node_compose_dir }}/{{ fabos_wazuh_default_compose_files[1] }}"
      dest: "{{ fabos_wazuh_default_docker_compose_dir }}/wazuh.yml"

- name: "WAZUH BACKEND | Modify Wazuh dashboard configuration"
  when: item.when
  ansible.builtin.lineinfile:
    path: "{{ fabos_wazuh_default_config_dir }}/wazuh_dashboard/opensearch_dashboards.yml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop:
    - when: "{{ not fabos_wazuh_default_dashboard_tls_enabled }}"
      regexp: '^server.ssl.enabled:'
      line: 'server.ssl.enabled: false'
    - when: "{{ fabos_wazuh_default_dashboard_base_url | length > 0 }}"
      regexp: '^server.basePath:'
      line: 'server.basePath: "{{ fabos_wazuh_default_dashboard_base_url }}"'
    - when: "{{ fabos_wazuh_default_dashboard_base_url | length == 0 }}"
      regexp: '^server.basePath:'
      state: absent
  register: dashboard_config_result

- name: WAZUH BACKEND | Replace volume path on host
  ansible.builtin.replace:
    path: "{{ fabos_wazuh_default_docker_compose_dir }}/{{ item }}"
    regexp: '\./config'
    replace: '{{ fabos_wazuh_default_config_dir }}'
  loop:
    - generate-indexer-certs.yml
    - wazuh.yml

- name: WAZUH BACKEND | Run docker compose workloads
  community.docker.docker_compose_v2:
    project_name: "{{ fabos_wazuh_compose_project_name | default('wazuh') }}"
    project_src: "{{ fabos_wazuh_default_docker_compose_dir }}"
    files: "{{ [item] }}"
    state: present
  register: compose_result
  changed_when:
    - compose_result is changed
    - '"Found orphan containers" not in compose_result.stderr'
  loop:
    - generate-indexer-certs.yml
    - wazuh.yml

- name: WAZUH BACKEND | Insert monitord keep log days option in config file
  ansible.builtin.lineinfile:
    path: "/var/lib/docker/volumes/{{ fabos_wazuh_compose_project_name | default('wazuh') }}_wazuh_etc/_data/local_internal_options.conf"
    regexp: '^monitord.keep_log_days='
    line: "monitord.keep_log_days={{ fabos_wazuh_backend_monitord_keep_log_days | default(1) }}"
    create: true
  notify: Restart Manager
